name: WAC-API
on:
  pull_request:
    types: [closed]
    branches: [main]
jobs:
  checkout:
    runs-on: self-hosted
    if: github.event.pull_request.merged
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  install:
    runs-on: self-hosted
    needs: checkout
    steps:
      - name: Install dependencies
        run: pnpm install

  e2e-test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Test
        run: |
          pnpm run test:e2e

  build:
    runs-on: self-hosted
    needs: e2e-test
    steps:
      - name: Build
        run: |
          pnpm run build

  run-server:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Run server
        run: |
          pm2 reload ecosystem.config.js
